### ISSUE TITLE
Use pythonic names

### ISSUE THREAD

**Issue by cthoyt** [darrenjw/jax-smfsb#8]
The repository uses very java-flavored names, which makes it less approachable for python programmers. You can read PEP-8's naming conventions guide to get familiar with https://peps.python.org/pep-0008/#naming-conventions

for example, `step = lvmod.stepGillespie()` feels very java. Python conventions would be to write it as `step = lvmod.step_gillespie()`

similarly, using the number 2 instead of `to` is also not very pythonic

https://github.com/darrenjw/jax-smfsb/blob/71a139c148c4b6c777c80a0bb71236a1fa834b6c/src/jsmfsb/smfsbSbml.py#L12

should be `mod_to_spn`, or ideally, something that is not an abbreviation

I understand that this might be because you're trying to mimic the interface of `smfsb`, but this is irrelevant in terms of reviewing this repo

**Comment by darrenjw** [comment]
OK, I've had a go at this. I don't like unnecessary breaking changes, but I do get your point. I've tried to make consistent changes to both this library and `smfsb`. Of course they are now both somewhat inconsistent with the R library and the Scala library, but I guess that's inevitable.

**Comment by cthoyt** [comment]
I'd highly suggest running the following in the root of your repo before considering this issue closed:

```
ruff check --select N
```

More information about how PEP-8 naming checks works here: https://docs.astral.sh/ruff/rules/#pep8-naming-n. I guess it might be initially frustrating to get errors like

```
tests/test_spatial.py:65:5: N806 Variable `N` in function should be lowercase
   |
63 | def test_step_cle_2d():
64 |     M=16
65 |     N=20
   |     ^ N806
66 |     x0 = jnp.zeros((2,M,N))
67 |     lv = jsmfsb.models.lv()
```

but, people who read your code will highly appreciate not having cryptic variable names everywhere

**Comment by darrenjw** [comment]
Have had a good go at cleaning up ruff suggestions
